# SPDX-FileCopyrightText: 2020 Volker Krause <vkrause@kde.org>
# SPDX-License-Identifier: CC0-1.0

include:
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/linux-qt6.yml
      - /gitlab-templates/linux-qt6-next.yml
      - /gitlab-templates/freebsd-qt6.yml
      - /gitlab-templates/xml-lint.yml
      - /gitlab-templates/yaml-lint.yml

# Verify changes against clang-format
clang-format:
  stage: build
  image: invent-registry.kde.org/sysadmin/ci-images/suse-qt610:latest
  tags:
    - Linux
  script:
    - git config --global --add safe.directory $CI_PROJECT_DIR
    - if [[ ! -f .clang-format && ! -f _clang-format ]]; then wget -O .clang-format https://invent.kde.org/frameworks/extra-cmake-modules/-/raw/master/kde-modules/clang-format.cmake; fi
    - git fetch origin master
    - git-clang-format --diff origin/master
