/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp org.kde.baloo.main.xml -a mainadaptor
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "mainadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class MainAdaptor
 */

MainAdaptor::MainAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

MainAdaptor::~MainAdaptor()
{
    // destructor
}

void MainAdaptor::quit()
{
    // handle method call org.kde.baloo.main.quit
    QMetaObject::invokeMethod(parent(), "quit");
}

void MainAdaptor::updateConfig()
{
    // handle method call org.kde.baloo.main.updateConfig
    QMetaObject::invokeMethod(parent(), "updateConfig");
}

